"""Generate a migration draft from the models and print it for review."""

import os
import sys
from pathlib import Path

from alembic import command
from alembic.config import Config

API_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(API_ROOT))

from app.config import get_settings, to_libpq_dsn  # noqa: E402

os.environ.setdefault(
    "ALEMBIC_DATABASE_URL",
    to_libpq_dsn(get_settings().test_database_url),
)

config = Config(str(API_ROOT / "alembic.ini"))
config.set_main_option("script_location", str(API_ROOT / "alembic"))

message = sys.argv[1] if len(sys.argv) > 1 else "autogenerated draft"
script = command.revision(config, message=message, autogenerate=True)

path = Path(script.path)
print("\n=== generated:", path.name, "===\n")
print(path.read_text(encoding="utf-8"))
